server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

spring:

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 3000MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloudstorage
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/main-changelog.xml

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis

  minio:
    url: http://localhost:9000
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
    bucket-name: user-files
